
# Configure Tomcat server:
server:
  port: 8080

# Point to the Eureka discovery client to it knows where to register:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  #Configure hearbeat interval:
  instance:
    leaseRenewalIntervalInSeconds: 60

# Assign a key to register with Discovery Service:
spring:
  application:
    name: user-service

# Configure Postgres:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres

# Configure the way JPA interacts with the database:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        globally-quoted-identifies: true

# Configure terminal output:
  output:
    ansi:
      enabled: always
logging:
  level:
    com:
      skillstorm: TRACE
    org:
      springframework: INFO
      apache:
        tomcat: ERROR